uint8 NONE=0            # Parameters: -
uint8 SPIN=1            # Parameters: r, g, b, speed
uint8 PULSE=2           # Parameters: r, g, b, speed
uint8 COLORS_SMOOTH=3   # Parameters: speed
uint8 WHEEL_COLORS=4    # Parameters: speed
uint8 COLORS_RGB=5      # Parameters: -
uint8 COLORS_SPIN=6     # Parameters: speed
uint8 MOTOR_DUTY=7      # Parameters: -
uint8 MOTOR_SPEEDS=8    # Parameters: -
uint8 SCAN_RANGES=9     # Parameters: left, right, front
uint8 mode
int16[] params
