driver:
  ros__parameters:
    device_name: "/dev/ttyACM0"
    baud_rate: 115200
    flow_control: "none"
    parity: "none"
    stop_bits: "one"
    plugin_odom: true
    plugin_motor: true
    plugin_led_module: true
    plugin_battery_state: true
