scan_filter_chain:
  - name: angle_filter
    type: laser_filters/LaserScanAngularBoundsFilter
    params:
      lower_angle: -1.5708  # -90 degrees in radians
      upper_angle: 1.5708   # +90 degrees in radians
