scan_filter_chain:
  - name: angle
    type: laser_filters/LaserScanAngularBoundsFilter
    params:
      lower_angle: -1.57  # Minimum angle in radians (-90 degrees)
      upper_angle: 1.57   # Maximum angle in radians (90 degrees)
